on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
  
jobs:
    build-and-test:
      runs-on: ${{ matrix.os }}
  
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
  
      steps:
        - uses: actions/checkout@v2
        - name: install cppunit
          run: |
            if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
              sudo apt install -y libcppunit-dev
            elif [ "${{ matrix.os }}" == "macos-latest" ]; then
              brew install cppunit
            elif [ "${{ matrix.os }}" == "windows-latest" ]; then
              choco install cppunit
            fi
        - name: configure
          run: ./configure
        - name: make
          run: make
        - name: make test
          run: make test