on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: |
          if ( "${{ matrix.os }}" == "ubuntu-latest" ) then
            sudo apt install -y libcppunit-dev
          elif ( "${{ matrix.os }}" == "macos-latest" ) then
            brew install cppunit
          fi
      - name: make
        run: |
          if ( "${{ matrix.os }}" == "ubuntu-latest" ) then
            make
          elif ( "${{ matrix.os }}" == "macos-latest" ) then
            clang++ -I. -std=c++17 -o test minesweeper.cpp test.cpp -lcppunit
          fi
      - name: make test
        run: |
          if ( "${{ matrix.os }}" == "ubuntu-latest" ) then
            make test
            exit_code=$?

            if [ $exit_code -eq 0 ]; then
              echo "All tests passed. Allowing push..."
              exit 0
            else
              echo "Tests failed. Blocking push..."
              exit 1
            fi
          elif ( "${{ matrix.os }}" == "macos-latest" ) then
            ./test
            if [ $? -eq 0 ]; then
              echo "All tests passed. Allowing push..."
              exit 0
            else
              echo "Tests failed. Blocking push..."
              exit 1
            fi
          fi
  
  win:
    runs-on: windows-latest
    steps:
      - name: install cppunit
        run: |
          dir "C:\Program Files (x86)\CppUnit\lib"