on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
  
jobs:
    build-and-test:
      runs-on: ${{ matrix.os }}
  
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
  
      steps:
        - uses: actions/checkout@v2
        
        - name: make
          run: make
        - name: make test
          run: |
            make test
            exit_code=$?

            if [ $exit_code -eq 0 ]; then
              echo "All tests passed. Allowing push..."
              exit 0
            else
              echo "Tests failed. Blocking push..."
              exit 1
            fi