on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: |
          if ( "${{ matrix.os }}" == "ubuntu-latest" ) {
            sudo apt install -y libcppunit-dev
          }
          elif ( "${{ matrix.os }}" == "macos-latest" ) {
            brew install cppunit
          }
          fi
      - name: make
        run: |
          if ( "${{ matrix.os }}" == "ubuntu-latest" ) {
            make
          }
          elif ( "${{ matrix.os }}" == "macos-latest" ) {
            clang++ -I. -std=c++17 -o test minesweeper.cpp test.cpp -lcppunit
          }
          fi
      - name: make test
        run: |
          if ( "${{ matrix.os }}" == "ubuntu-latest" ) {
            make test
            exit_code=$?

            if [ $exit_code -eq 0 ]; {
              echo "All tests passed. Allowing push..."
              exit 0
            }
            else
            {
              echo "Tests failed. Blocking push..."
              exit
            }
            fi
          }
          elif ( "${{ matrix.os }}" == "macos-latest" ) {
            ./test
            if [ $? -eq 0 ]{
              echo "All tests passed. Allowing push..."
              exit 0
            }
            else{
              echo "Tests failed. Blocking push..."
              exit 1
            }
          }